### ISSUE TITLE
upgrade all packages for full support of null-safety

### ISSUE THREAD

**Issue by ghost** [samflab/Fitility-OpenSource#106]
Hi @samflab ,

Hope you are all well ! and happy new year !

I was playing with your great project and one thing that was obvious to me is that you should maybe upgrade all packages for full null-safety support

some hints :-)
```yaml
  toast:
    git:
      url: https://github.com/appdev/FlutterToast
  carousel_pro:
    git: https://github.com/SherlockHolmes2045/flutter-carousel-pro
  progress_dialog:
    git: https://github.com/mostafaAbdelazim/progress_dialog.git
```

What do you think about that ?

Cheers,
Luc
